Validation and/or decryption SignedEncryptedPseudonym with diversifier fails - Alternate Flow
=============================================================================================
Tags: signed-encrypted-pseudonym,diversifier,alternate-flow,@bsnkeiddo-4788@

* Load dataset from "/v1/signed-encrypted-pseudonym/alternate_flows_diversifier.yaml"
* Target default endpoint "/signed-encrypted-pseudonym"

### Given

A SignedEncryptedPseudonym with diversifier, SP-key, schemekey and closingkey is provided as input for the decryption component

### When

The SignedEncryptedPseudonym and/or keys are invalid or the combination does not match

### Then

No Pseudonym is returned in the response message with corresponding error status

### Description

error flows
-- EP with diversifier - invalid signature

The *auditElement* and *signatureValue* have no static values and will change when new
test data is generated. When new test data is generated by Logius, the corresponding expected
test results are produced as well.


Scenario 1: SignedEncryptedPseudonym with diversifier 1 invalid signed
----------------------------------------------------------------------
Tags: @bsnkeiddo-4802@

* Create OASSignedEncryptedPseudonymRequest
    | propertyName                  | propertyValue                                                             | propertyFilter          |
    |-------------------------------|---------------------------------------------------------------------------|-------------------------|
    | signedEncryptedPseudonym      | {{ scenario_1.request.signedEncryptedPseudonym                            | binary              }}  |
    | schemeKeys                    | {{ scenario_1.request.schemeKeys                                          | schemeKeys          }}  |
    | serviceProviderKeys           | {{ scenario_1.request.serviceProviderKeys                                 | serviceProviderKeys }}  |
    | targetClosingKey              | {{ scenario_1.request.targetClosingKey                                    | string              }}  |
* Send OASSignedEncryptedPseudonymRequest
* Expect response matches
    | actualValue                                           | expectedValue                                                    | expectedValueType    |
    |-------------------------------------------------------|------------------------------------------------------------------|----------------------|
    | statusCode                                            | {{ scenario_1.expectations.statusCode                            | string          }}   |
* Expect response body contains "SIGNATURE_VERIFICATION_FAILED"
* Fail if expectations are not met



Scenario 2: SignedEncryptedPseudonym with diversifier 2 invalid signed
----------------------------------------------------------------------
Tags: @bsnkeiddo-4848@

* Create OASSignedEncryptedPseudonymRequest
    | propertyName                  | propertyValue                                                             | propertyFilter          |
    |-------------------------------|---------------------------------------------------------------------------|-------------------------|
    | signedEncryptedPseudonym      | {{ scenario_1.request.signedEncryptedPseudonym                            | binary              }}  |
    | schemeKeys                    | {{ scenario_1.request.schemeKeys                                          | schemeKeys          }}  |
    | serviceProviderKeys           | {{ scenario_1.request.serviceProviderKeys                                 | serviceProviderKeys }}  |
    | targetClosingKey              | {{ scenario_1.request.targetClosingKey                                    | string              }}  |
* Send OASSignedEncryptedPseudonymRequest
* Expect response matches
    | actualValue                                           | expectedValue                                                    | expectedValueType    |
    |-------------------------------------------------------|------------------------------------------------------------------|----------------------|
    | statusCode                                            | {{ scenario_1.expectations.statusCode                            | string          }}   |
* Expect response body contains "SIGNATURE_VERIFICATION_FAILED"
* Fail if expectations are not met



Scenario 3: SignedEncryptedPseudonym with diversifier 3 invalid signed
----------------------------------------------------------------------
Tags: @bsnkeiddo-4849@

* Create OASSignedEncryptedPseudonymRequest
    | propertyName                  | propertyValue                                                             | propertyFilter          |
    |-------------------------------|---------------------------------------------------------------------------|-------------------------|
    | signedEncryptedPseudonym      | {{ scenario_1.request.signedEncryptedPseudonym                            | binary              }}  |
    | schemeKeys                    | {{ scenario_1.request.schemeKeys                                          | schemeKeys          }}  |
    | serviceProviderKeys           | {{ scenario_1.request.serviceProviderKeys                                 | serviceProviderKeys }}  |
    | targetClosingKey              | {{ scenario_1.request.targetClosingKey                                    | string              }}  |
* Send OASSignedEncryptedPseudonymRequest
* Expect response matches
    | actualValue                                           | expectedValue                                                    | expectedValueType    |
    |-------------------------------------------------------|------------------------------------------------------------------|----------------------|
    | statusCode                                            | {{ scenario_1.expectations.statusCode                            | string          }}   |
* Expect response body contains "SIGNATURE_VERIFICATION_FAILED"
* Fail if expectations are not met
