package nl.logius.pepcrypto.lib.pem;

import nl.logius.pepcrypto.lib.lang.PepExceptionDetail;

public enum PemExceptionDetail
        implements PepExceptionDetail {

    PEM_OBJECT_READ_FAILED,
    PEM_KEY_UNSUPPORTED_PEM_TYPE,

    PEM_HEADERS_INVALID,
    PEM_PRIVATE_KEY_INFO_DECODE_FAILED,
    PEM_PRIVATE_KEY_VALUE_DECODE,
    PEM_EC_PRIVATE_KEY_NOT_FOUND,
    PEM_EC_PRIVATE_KEY_DECODE,
    PEM_EC_PRIVATE_KEY_SCHEME_VERSION,
    PEM_EC_PRIVATE_KEY_CURVE_OID,
    PEM_EC_PRIVATE_KEY_BYTE_LENGTH,

    PEM_PUBLIC_KEY_VALUE_DECODE,

    PEM_KEY_UNSUPPORTED_SCHEME_VERSION,
    PEM_PRIVATE_KEY_VALUE_INVALID,
    PEM_KEY_RECIPIENT_KEY_PUBLIC_KEY_INVALID,
    PEM_KEY_UNSUPPORTED_RECIPIENT_KEY_TYPE,
    PEM_HEADER_MISSING_REQUIRED_HEADER,
    PEM_HEADER_DUPLICATE_HEADERS,

    /**
     * Unspecified exception in PEM-module.
     */
    PEM_MODULE,

}

